/* The following code was generated by JFlex 1.4.3 on 8/06/23 16:02 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/06/23 16:02 from the specification file
 * <tt>C:/Users/TH_Invitado/Desktop/Java/AnalizadorSintactico/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\66\1\41\1\6\1\55"+
    "\1\0\1\44\1\37\1\0\1\45\1\46\1\36\1\34\1\65\1\35"+
    "\1\57\1\4\12\2\1\7\1\54\1\43\1\33\1\42\2\0\22\1"+
    "\1\27\7\1\1\51\1\0\1\52\1\0\1\61\1\0\1\16\1\10"+
    "\1\14\1\25\1\13\1\24\1\23\1\15\1\30\1\1\1\60\1\20"+
    "\1\53\1\22\1\21\1\56\1\1\1\17\1\31\1\12\1\26\1\63"+
    "\1\32\1\62\1\11\1\64\1\47\1\40\1\50\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\20\2\1\11\1\12\1\13\1\14\3\15\2\16"+
    "\1\1\1\17\1\20\1\21\1\22\1\23\1\24\1\2"+
    "\1\25\1\1\2\2\1\26\1\4\1\27\1\0\1\30"+
    "\31\2\1\31\4\2\1\32\5\2\1\16\1\33\1\15"+
    "\1\34\3\0\1\35\1\0\2\2\1\0\13\2\1\36"+
    "\7\2\1\37\1\40\5\2\1\41\4\2\1\42\12\2"+
    "\1\43\5\2\10\0\2\2\1\0\6\2\1\44\1\2"+
    "\1\45\3\2\1\46\1\47\1\50\2\2\1\51\1\52"+
    "\26\2\7\0\1\3\1\53\1\2\1\0\4\2\1\54"+
    "\1\2\1\55\4\2\1\56\1\2\1\57\10\2\1\60"+
    "\1\2\1\61\4\2\1\62\3\2\1\63\10\0\1\2"+
    "\1\0\7\2\1\64\2\2\1\65\4\2\1\66\3\2"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\6\0"+
    "\1\2\1\0\2\2\1\76\3\2\1\77\7\2\1\100"+
    "\2\2\1\101\3\0\1\102\1\0\1\2\1\103\1\2"+
    "\1\104\1\105\1\106\1\107\1\110\1\2\1\111\2\2"+
    "\1\112\1\2\1\113\1\2\1\114\1\2\1\115\2\2"+
    "\1\116\5\2\1\117\1\2\1\120\3\2\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\67\0\u014a"+
    "\0\67\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u04f1"+
    "\0\u063b\0\u0672\0\u0596\0\u06a9\0\67\0\67\0\67\0\67"+
    "\0\67\0\u06e0\0\67\0\u0717\0\u074e\0\u0785\0\67\0\u07bc"+
    "\0\67\0\u014a\0\67\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87"+
    "\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f"+
    "\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\156\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\67"+
    "\0\67\0\67\0\67\0\u0f78\0\u0faf\0\u0fe6\0\67\0\u101d"+
    "\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5"+
    "\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\156\0\u1356"+
    "\0\u138d\0\u13c4\0\u13fb\0\u1432\0\u1469\0\u14a0\0\156\0\156"+
    "\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\156\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\156\0\u16c6\0\u16fd\0\u1734\0\u176b\0\u17a2"+
    "\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5\0\156\0\u18ec\0\u1923"+
    "\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4\0\u1adb"+
    "\0\u1b12\0\u1b49\0\u1b80\0\u1bb7\0\u1bee\0\u1c25\0\u1c5c\0\u1c93"+
    "\0\u1cca\0\u1d01\0\u1d38\0\u1d6f\0\156\0\u1da6\0\156\0\u1ddd"+
    "\0\u1e14\0\u1e4b\0\156\0\156\0\156\0\u1e82\0\u1eb9\0\156"+
    "\0\156\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95\0\u1fcc\0\u2003\0\u203a"+
    "\0\u2071\0\u20a8\0\u20df\0\u2116\0\u214d\0\u2184\0\u21bb\0\u21f2"+
    "\0\u2229\0\u2260\0\u2297\0\u22ce\0\u2305\0\u233c\0\u2373\0\u23aa"+
    "\0\u23e1\0\u2418\0\u244f\0\u2486\0\u24bd\0\u24f4\0\67\0\156"+
    "\0\u252b\0\u2562\0\u2599\0\u25d0\0\u2607\0\u263e\0\156\0\u2675"+
    "\0\156\0\u26ac\0\u26e3\0\u271a\0\u2751\0\156\0\u2788\0\156"+
    "\0\u27bf\0\u27f6\0\u282d\0\u2864\0\u289b\0\u28d2\0\u2909\0\u2940"+
    "\0\156\0\u2977\0\156\0\u29ae\0\u29e5\0\u2a1c\0\u2a53\0\156"+
    "\0\u2a8a\0\u2ac1\0\u2af8\0\156\0\u2b2f\0\u2b66\0\u2b9d\0\u2bd4"+
    "\0\u2c0b\0\u2c42\0\u2c79\0\u2cb0\0\u2ce7\0\u2d1e\0\u2d55\0\u2d8c"+
    "\0\u2dc3\0\u2dfa\0\u2e31\0\u2e68\0\u2e9f\0\156\0\u2ed6\0\u2f0d"+
    "\0\156\0\u2f44\0\u2f7b\0\u2fb2\0\u2fe9\0\156\0\u3020\0\u3057"+
    "\0\u308e\0\156\0\156\0\u30c5\0\156\0\156\0\156\0\156"+
    "\0\u30fc\0\u3133\0\u316a\0\u31a1\0\u31d8\0\u320f\0\u3246\0\u327d"+
    "\0\u32b4\0\u32eb\0\156\0\u3322\0\u3359\0\u3390\0\156\0\u33c7"+
    "\0\u33fe\0\u3435\0\u346c\0\u34a3\0\u34da\0\u3511\0\156\0\u3548"+
    "\0\u357f\0\67\0\u35b6\0\u35ed\0\u3624\0\156\0\u365b\0\u3692"+
    "\0\156\0\u36c9\0\156\0\156\0\156\0\156\0\156\0\u3700"+
    "\0\156\0\u3737\0\u376e\0\156\0\u37a5\0\67\0\u37dc\0\156"+
    "\0\u3813\0\156\0\u384a\0\u3881\0\156\0\u38b8\0\u38ef\0\u3926"+
    "\0\u395d\0\u3994\0\156\0\u39cb\0\156\0\u3a02\0\u3a39\0\u3a70"+
    "\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\3\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\2"+
    "\3\3\1\56\1\3\2\5\70\0\2\3\5\0\23\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\3\0"+
    "\1\4\67\0\1\5\61\0\2\5\4\0\1\60\26\0"+
    "\1\61\34\0\2\62\3\0\1\63\1\0\23\62\20\0"+
    "\1\62\2\0\1\62\1\0\5\62\1\0\1\62\1\0"+
    "\2\3\5\0\1\3\1\64\5\3\1\65\1\3\1\66"+
    "\11\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\1\3\1\67\1\3\1\70\1\3"+
    "\1\71\1\3\1\72\13\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\10\3\1\73"+
    "\12\3\20\0\1\3\2\0\1\3\1\0\2\3\1\74"+
    "\2\3\1\57\2\0\2\3\5\0\5\3\1\75\1\76"+
    "\2\3\1\77\6\3\1\100\2\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\21\3"+
    "\1\101\1\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\3\3\1\102\17\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\11\3\1\103\11\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\23\3\20\0"+
    "\1\3\2\0\1\104\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\3\3\1\105\2\3\1\106\14\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\6\3\1\107\1\110\1\111\1\112\11\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\1\3\1\113\1\3\1\114\5\3\1\115\11\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\12\3\1\116\6\3\1\117\1\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\2\3\1\120\20\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\12\3\1\121\1\3"+
    "\1\122\6\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\2\3\1\123\2\3\1\124"+
    "\12\3\1\125\1\3\1\126\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\5\3\1\127"+
    "\15\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\34\0\1\130\66\0\1\61\1\131\65\0\1\61\1\0"+
    "\1\131\64\0\1\61\72\0\1\132\67\0\1\132\61\0"+
    "\1\130\6\0\1\133\40\0\1\134\2\0\1\135\10\0"+
    "\1\136\2\0\1\130\7\0\1\137\60\0\1\140\32\0"+
    "\2\3\5\0\6\3\1\141\7\3\1\142\4\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\31\0\1\143"+
    "\37\0\2\3\5\0\7\3\1\144\6\3\1\145\4\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\11\3\1\146\6\3\1\147\2\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\1\0\5\60"+
    "\1\0\61\60\1\0\2\3\5\0\2\3\1\150\20\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\151\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\11\3"+
    "\1\152\11\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\23\3\20\0\1\3\2\0"+
    "\1\153\1\0\5\3\1\57\2\0\2\3\5\0\23\3"+
    "\20\0\1\154\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\7\3\1\155\10\3\1\156\2\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\1\3\1\157\14\3\1\160\4\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\21\3\1\161\1\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\23\3\20\0\1\3"+
    "\2\0\1\162\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\6\3\1\163\14\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\2\3\1\164\16\3"+
    "\1\165\1\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\16\3\1\166\4\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\12\3\1\167\10\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\23\3\20\0"+
    "\1\170\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\2\3\1\171\10\3\1\172\4\3\1\173\2\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\12\3\1\174\10\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\3\3"+
    "\1\175\17\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\22\3\1\176\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\23\3\20\0\1\177\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\10\3\1\200\12\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\20\3\1\201\2\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\11\3\1\202\11\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\7\3\1\203\13\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\12\3"+
    "\1\204\10\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\14\3\1\205\6\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\16\3\1\206\4\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\20\3\1\207"+
    "\1\210\1\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\20\3\1\211\2\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\7\3\1\212\13\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\10\3\1\213"+
    "\12\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\6\3\1\214\1\215\5\3\1\216"+
    "\5\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\11\3\1\217\11\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\13\3\1\220\7\3\20\0\1\3\2\0\1\3\1\0"+
    "\4\3\1\221\1\57\2\0\2\3\5\0\20\3\1\222"+
    "\2\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\20\3\1\223\2\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\13\0\1\224\1\0"+
    "\1\225\4\0\1\226\7\0\1\227\21\0\1\230\31\0"+
    "\1\231\71\0\1\232\47\0\1\233\65\0\2\3\5\0"+
    "\20\3\1\234\2\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\2\3\1\235\20\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\23\0"+
    "\1\236\45\0\2\3\5\0\11\3\1\237\6\3\1\240"+
    "\2\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\1\241\22\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\10\3"+
    "\1\242\7\3\1\243\2\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\7\3\1\244"+
    "\13\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\3\3\1\245\17\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\6\3\1\246\14\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\10\3\1\247\12\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\250\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\23\3"+
    "\20\0\1\3\2\0\1\251\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\11\3\1\252\11\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\21\3"+
    "\1\253\1\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\3\3\1\254\17\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\3\3\1\255\17\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\10\3\1\256"+
    "\12\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\7\3\1\245\13\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\4\3\1\257\16\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\3\3\1\260\17\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\2\3\1\261\20\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\16\3"+
    "\1\262\4\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\20\3\1\263\2\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\12\3\1\264\10\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\13\3\1\245"+
    "\7\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\7\3\1\265\13\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\3\3\1\266\17\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\21\3\1\160\1\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\267\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\6\3"+
    "\1\270\14\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\6\3\1\271\14\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\6\3\1\272\14\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\1\273\22\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\11\3\1\274\11\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\20\3"+
    "\1\275\2\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\12\3\1\276\10\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\20\3\1\277\2\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\20\3\1\300"+
    "\2\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\2\3\1\301\20\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\16\3\1\302\4\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\7\3\1\303\13\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\12\3\1\304\10\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\3\3"+
    "\1\305\17\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\2\3\1\306\20\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\10\3\1\307\12\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\31\0\1\310\50\0\1\311\76\0"+
    "\1\312\56\0\1\313\72\0\1\314\72\0\1\315\75\0"+
    "\1\316\37\0\1\233\43\0\1\317\21\0\2\3\5\0"+
    "\12\3\1\320\10\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\6\3\1\321\14\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\15\0"+
    "\1\322\53\0\2\3\5\0\2\3\1\323\20\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\23\3\20\0\1\3\2\0\1\3\1\0\3\3"+
    "\1\324\1\3\1\57\2\0\2\3\5\0\10\3\1\325"+
    "\12\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\6\3\1\326\14\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\15\3\1\327\5\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\2\3\1\330\20\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\23\3\20\0\1\3\2\0\1\3\1\0"+
    "\1\331\4\3\1\57\2\0\2\3\5\0\12\3\1\332"+
    "\2\3\1\333\2\3\1\334\2\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\10\3"+
    "\1\335\12\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\22\3\1\336\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\20\3\1\337\2\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\5\3\1\340\15\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\7\3\1\341\13\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\21\3"+
    "\1\342\1\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\2\3\1\343\20\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\6\3\1\344\14\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\21\3\1\345"+
    "\1\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\12\3\1\346\10\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\2\3\1\245\20\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\23\3\20\0\1\347"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\16\3\1\350\4\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\10\3\1\150\12\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\12\3\1\351\10\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\13\3"+
    "\1\352\7\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\13\3\1\353\7\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\12\3\1\354\10\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\12\3\1\355"+
    "\10\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\20\3\1\356\2\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\4\3\1\357\16\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\2\3\1\360\20\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\361\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\11\3"+
    "\1\362\11\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\4\3\1\363\16\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\3\3\1\364\17\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\54\0\1\365\24\0\1\366\105\0"+
    "\1\367\55\0\1\370\5\0\1\371\53\0\1\372\101\0"+
    "\1\373\53\0\1\374\55\0\2\3\5\0\1\375\22\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\21\0"+
    "\1\376\47\0\2\3\5\0\3\3\1\377\17\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\6\3\1\u0100\14\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\20\3\1\u0101"+
    "\2\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\2\3\1\u0102\20\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\16\3\1\u0103\4\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\6\3\1\u0104\14\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\u0105\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\15\3"+
    "\1\u0106\5\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\6\3\1\u0107\14\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\4\3\1\u0108\16\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\12\3\1\u0109"+
    "\10\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\2\3\1\u010a\20\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\3\3\1\u010b\17\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\2\3\1\u010c\20\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\23\3\20\0\1\3\2\0\1\u010d\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\15\3\1\u010e\5\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\20\3\1\u010f\2\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\10\3"+
    "\1\u0110\12\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\12\3\1\u0111\10\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\13\3\1\u0112\7\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\3\3\1\u0113"+
    "\17\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\4\3\1\u0114\16\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\2\3\1\u0115\20\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\15\3\1\u0116\5\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\14\3\1\u0117\6\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\5\3"+
    "\1\u0118\15\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\14\0\1\u0119\131\0\1\365\31\0\1\u011a\75\0"+
    "\1\u011b\56\0\1\u011c\63\0\1\u0119\72\0\1\u011d\64\0"+
    "\1\u011e\50\0\2\3\5\0\10\3\1\u011f\12\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\27\0\1\u0120"+
    "\41\0\2\3\5\0\4\3\1\u0121\16\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\2\3\1\u0122\20\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\4\3\1\u0123\16\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\20\3\1\u0124\2\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\6\3"+
    "\1\u0125\14\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\23\3\20\0\1\u0126\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\14\3"+
    "\1\u0127\6\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\2\3\1\u0128\20\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\20\3\1\u0129\2\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\3\3\1\u012a"+
    "\17\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\7\3\1\u012b\13\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\11\3\1\u012c\11\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\6\3\1\u012d\14\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\4\3\1\u012e\16\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\2\3"+
    "\1\u012f\20\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\3\3\1\u0130\17\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\23\3\20\0\1\3\2\0\1\3\1\0\1\3"+
    "\1\u0131\3\3\1\57\43\0\1\u0132\103\0\1\372\31\0"+
    "\1\u0133\74\0\1\u0134\111\0\1\u0119\26\0\1\u0135\54\0"+
    "\2\3\5\0\3\3\1\u0136\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\26\0\1\u0137\42\0\2\3"+
    "\5\0\2\3\1\u0138\20\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\3\3\1\u0139"+
    "\17\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\10\3\1\u013a\12\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\10\3\1\u013b\12\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\3\3\1\u013c\17\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\u013d\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\2\3"+
    "\1\u013e\20\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\7\3\1\u013f\13\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\23\3\20\0\1\3\2\0\1\u0140\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\7\3\1\u0141\13\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\4\3\1\u0142\16\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\23\3\20\0"+
    "\1\3\2\0\1\3\1\0\1\3\1\u0143\3\3\1\57"+
    "\2\0\2\3\5\0\15\3\1\u0144\5\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\4\3\1\u0145\16\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\24\0\1\u0119\53\0\1\u0119\74\0\1\u011d"+
    "\63\0\1\u0146\54\0\2\3\5\0\3\3\1\u0147\17\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\3\3\1\u0148\17\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\7\3"+
    "\1\u0149\13\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\3\3\1\u014a\17\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\4\3\1\u014b\16\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\6\3\1\u014c"+
    "\14\3\20\0\1\3\2\0\1\3\1\0\5\3\1\57"+
    "\2\0\2\3\5\0\15\3\1\u014d\5\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\3\3\1\u014e\17\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\6\3\1\u014f\14\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\21\3\1\u0150\1\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\2\3"+
    "\1\u0151\20\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\2\0\2\3\5\0\21\3\1\u0152\1\3\20\0"+
    "\1\3\2\0\1\3\1\0\5\3\1\57\2\0\2\3"+
    "\5\0\2\3\1\u0153\20\3\20\0\1\3\2\0\1\3"+
    "\1\0\5\3\1\57\2\0\2\3\5\0\23\3\20\0"+
    "\1\3\2\0\1\3\1\0\1\3\1\u0154\3\3\1\57"+
    "\2\0\2\3\5\0\2\3\1\u0155\20\3\20\0\1\3"+
    "\2\0\1\3\1\0\5\3\1\57\2\0\2\3\5\0"+
    "\4\3\1\u0156\16\3\20\0\1\3\2\0\1\3\1\0"+
    "\5\3\1\57\2\0\2\3\5\0\6\3\1\u0157\14\3"+
    "\20\0\1\3\2\0\1\3\1\0\5\3\1\57\2\0"+
    "\2\3\5\0\21\3\1\u0158\1\3\20\0\1\3\2\0"+
    "\1\3\1\0\5\3\1\57\2\0\2\3\5\0\2\3"+
    "\1\u0159\20\3\20\0\1\3\2\0\1\3\1\0\5\3"+
    "\1\57\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15015];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\1\11\33\1\5\11"+
    "\1\1\1\11\3\1\1\11\1\1\1\11\1\0\1\11"+
    "\44\1\4\11\3\0\1\11\1\0\2\1\1\0\60\1"+
    "\10\0\2\1\1\0\51\1\7\0\1\11\2\1\1\0"+
    "\42\1\10\0\1\1\1\0\32\1\6\0\1\1\1\0"+
    "\21\1\1\11\3\0\1\1\1\0\16\1\1\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 29: 
          { lexeme=yytext(); return Doble_Menor;
          }
        case 82: break;
        case 48: 
          { lexeme=yytext(); return Union;
          }
        case 83: break;
        case 51: 
          { lexeme=yytext(); return While;
          }
        case 84: break;
        case 60: 
          { lexeme=yytext(); return Sizeof;
          }
        case 85: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 86: break;
        case 28: 
          { lexeme=yytext(); return Doble_Mayor;
          }
        case 87: break;
        case 42: 
          { lexeme=yytext(); return Cout;
          }
        case 88: break;
        case 45: 
          { lexeme=yytext(); return Break;
          }
        case 89: break;
        case 15: 
          { lexeme=yytext(); return Parentesis_a;
          }
        case 90: break;
        case 76: 
          { lexeme=yytext(); return Volatile;
          }
        case 91: break;
        case 40: 
          { lexeme=yytext(); return Else;
          }
        case 92: break;
        case 74: 
          { lexeme=yytext(); return Unsigned;
          }
        case 93: break;
        case 43: 
          { lexeme=yytext(); return Main;
          }
        case 94: break;
        case 41: 
          { lexeme=yytext(); return Case;
          }
        case 95: break;
        case 38: 
          { lexeme=yytext(); return This;
          }
        case 96: break;
        case 4: 
          { /*Ignore*/
          }
        case 97: break;
        case 79: 
          { lexeme=yytext(); return Static_cast;
          }
        case 98: break;
        case 49: 
          { lexeme=yytext(); return Using;
          }
        case 99: break;
        case 32: 
          { lexeme=yytext(); return Asm;
          }
        case 100: break;
        case 13: 
          { lexeme=yytext(); return Op_logico;
          }
        case 101: break;
        case 67: 
          { lexeme=yytext(); return Private;
          }
        case 102: break;
        case 66: 
          { lexeme=yytext(); return Mutable;
          }
        case 103: break;
        case 54: 
          { lexeme=yytext(); return Friend;
          }
        case 104: break;
        case 47: 
          { lexeme=yytext(); return Catch;
          }
        case 105: break;
        case 81: 
          { lexeme=yytext(); return Reinterpret_cast;
          }
        case 106: break;
        case 72: 
          { lexeme=yytext(); return Register;
          }
        case 107: break;
        case 18: 
          { lexeme=yytext(); return Llave_c;
          }
        case 108: break;
        case 20: 
          { lexeme = yytext(); return Corchete_c;
          }
        case 109: break;
        case 1: 
          { return ERROR;
          }
        case 110: break;
        case 33: 
          { lexeme=yytext(); return New;
          }
        case 111: break;
        case 39: 
          { lexeme = yytext(); return Op_booleano;
          }
        case 112: break;
        case 25: 
          { lexeme=yytext(); return Do;
          }
        case 113: break;
        case 21: 
          { lexeme=yytext(); return P_coma;
          }
        case 114: break;
        case 31: 
          { lexeme=yytext(); return Cin;
          }
        case 115: break;
        case 11: 
          { lexeme=yytext(); return Resta;
          }
        case 116: break;
        case 14: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 117: break;
        case 68: 
          { lexeme=yytext(); return Virtual;
          }
        case 118: break;
        case 24: 
          { lexeme=yytext(); return Palabra;
          }
        case 119: break;
        case 22: 
          { lexeme=yytext(); return Variables;
          }
        case 120: break;
        case 44: 
          { lexeme=yytext(); return Void;
          }
        case 121: break;
        case 59: 
          { lexeme=yytext(); return Signed;
          }
        case 122: break;
        case 35: 
          { lexeme=yytext(); return Espacio_de_Nombre;
          }
        case 123: break;
        case 56: 
          { lexeme=yytext(); return Inline;
          }
        case 124: break;
        case 9: 
          { lexeme=yytext(); return Igual;
          }
        case 125: break;
        case 57: 
          { lexeme=yytext(); return Static;
          }
        case 126: break;
        case 55: 
          { lexeme=yytext(); return Cadena;
          }
        case 127: break;
        case 10: 
          { lexeme=yytext(); return Suma;
          }
        case 128: break;
        case 27: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 129: break;
        case 69: 
          { lexeme=yytext(); return Typename;
          }
        case 130: break;
        case 63: 
          { lexeme=yytext(); return Typedef;
          }
        case 131: break;
        case 36: 
          { lexeme=yytext(); return T_dato;
          }
        case 132: break;
        case 23: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 133: break;
        case 75: 
          { lexeme=yytext(); return Include;
          }
        case 134: break;
        case 17: 
          { lexeme=yytext(); return Llave_a;
          }
        case 135: break;
        case 53: 
          { lexeme=yytext(); return Return;
          }
        case 136: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 137: break;
        case 52: 
          { lexeme=yytext(); return Typeid;
          }
        case 138: break;
        case 34: 
          { lexeme=yytext(); return For;
          }
        case 139: break;
        case 19: 
          { lexeme = yytext(); return Corchete_a;
          }
        case 140: break;
        case 26: 
          { lexeme=yytext(); return If;
          }
        case 141: break;
        case 70: 
          { lexeme=yytext(); return Template;
          }
        case 142: break;
        case 37: 
          { lexeme=yytext(); return Bool;
          }
        case 143: break;
        case 6: 
          { return Linea;
          }
        case 144: break;
        case 46: 
          { lexeme=yytext(); return Throw;
          }
        case 145: break;
        case 16: 
          { lexeme=yytext(); return Parentesis_c;
          }
        case 146: break;
        case 58: 
          { lexeme=yytext(); return Struct;
          }
        case 147: break;
        case 8: 
          { lexeme=yytext(); return Dos_P;
          }
        case 148: break;
        case 64: 
          { lexeme=yytext(); return Default;
          }
        case 149: break;
        case 62: 
          { lexeme=yytext(); return Public;
          }
        case 150: break;
        case 65: 
          { lexeme=yytext(); return Libreria;
          }
        case 151: break;
        case 77: 
          { lexeme=yytext(); return NameSpace;
          }
        case 152: break;
        case 30: 
          { lexeme=yytext(); return Try;
          }
        case 153: break;
        case 80: 
          { lexeme=yytext(); return Dynamic_cast;
          }
        case 154: break;
        case 73: 
          { lexeme=yytext(); return Operator;
          }
        case 155: break;
        case 61: 
          { lexeme=yytext(); return Switch;
          }
        case 156: break;
        case 7: 
          { lexeme=yytext(); return Comillas;
          }
        case 157: break;
        case 78: 
          { lexeme=yytext(); return Protected;
          }
        case 158: break;
        case 5: 
          { lexeme=yytext(); return Division;
          }
        case 159: break;
        case 50: 
          { lexeme=yytext(); return Short;
          }
        case 160: break;
        case 12: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 161: break;
        case 71: 
          { lexeme=yytext(); return Explicit;
          }
        case 162: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
