
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 30 03:52:32 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Public = 64;
  public static final int Op_atribucion = 20;
  public static final int Parentesis_c = 24;
  public static final int Return = 67;
  public static final int Op_booleano = 22;
  public static final int Parentesis_a = 23;
  public static final int Llave_c = 26;
  public static final int Mutable = 59;
  public static final int Llave_a = 25;
  public static final int Libreria = 40;
  public static final int Linea = 2;
  public static final int Break = 45;
  public static final int Corchete_c = 28;
  public static final int True = 78;
  public static final int Corchete_a = 27;
  public static final int Long = 58;
  public static final int Default = 41;
  public static final int Char = 47;
  public static final int For = 12;
  public static final int Void = 87;
  public static final int Else = 8;
  public static final int Try = 79;
  public static final int Resta = 15;
  public static final int Int = 5;
  public static final int Espacio_de_Nombre = 35;
  public static final int This = 76;
  public static final int Suma = 14;
  public static final int Using = 33;
  public static final int ERROR = 90;
  public static final int Cadena = 6;
  public static final int Typedef = 80;
  public static final int T_dato = 4;
  public static final int Main = 29;
  public static final int Do = 9;
  public static final int Static = 71;
  public static final int Private = 62;
  public static final int Op_relacional = 19;
  public static final int P_coma = 31;
  public static final int Unsigned = 84;
  public static final int Signed = 69;
  public static final int Typeid = 81;
  public static final int Operator = 61;
  public static final int Short = 68;
  public static final int Template = 75;
  public static final int Case = 42;
  public static final int Volatile = 88;
  public static final int New = 60;
  public static final int Const = 50;
  public static final int Variables = 85;
  public static final int Continue = 51;
  public static final int Dynamic_cast = 53;
  public static final int Sizeof = 70;
  public static final int Auto = 44;
  public static final int If = 7;
  public static final int Dos_P = 10;
  public static final int EOF = 0;
  public static final int Virtual = 86;
  public static final int Catch = 46;
  public static final int Bool = 89;
  public static final int Throw = 77;
  public static final int Cout = 30;
  public static final int Typename = 82;
  public static final int Numero = 36;
  public static final int Struct = 73;
  public static final int Division = 17;
  public static final int Friend = 56;
  public static final int Doble_Menor = 38;
  public static final int Asm = 43;
  public static final int error = 1;
  public static final int Static_cast = 72;
  public static final int False = 55;
  public static final int Inline = 57;
  public static final int NameSpace = 34;
  public static final int Comillas = 3;
  public static final int Explicit = 54;
  public static final int Identificador = 32;
  public static final int Op_incremento = 21;
  public static final int Reinterpret_cast = 66;
  public static final int Include = 39;
  public static final int Class = 48;
  public static final int Cons_cast = 49;
  public static final int Register = 65;
  public static final int Palabra = 37;
  public static final int Delete = 52;
  public static final int Igual = 13;
  public static final int Union = 83;
  public static final int While = 11;
  public static final int Op_logico = 18;
  public static final int Switch = 74;
  public static final int Multiplicacion = 16;
  public static final int Protected = 63;
}

