
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 08 15:11:04 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Public = 66;
  public static final int Op_atribucion = 22;
  public static final int Parentesis_c = 26;
  public static final int Return = 69;
  public static final int Op_booleano = 24;
  public static final int Parentesis_a = 25;
  public static final int Llave_c = 28;
  public static final int Mutable = 61;
  public static final int Llave_a = 27;
  public static final int Libreria = 42;
  public static final int Linea = 2;
  public static final int Break = 47;
  public static final int Corchete_c = 30;
  public static final int True = 80;
  public static final int Corchete_a = 29;
  public static final int Long = 60;
  public static final int Default = 43;
  public static final int Char = 49;
  public static final int For = 14;
  public static final int Void = 89;
  public static final int Else = 10;
  public static final int Try = 81;
  public static final int Resta = 17;
  public static final int Int = 7;
  public static final int Doble_Mayor = 5;
  public static final int Espacio_de_Nombre = 37;
  public static final int Cin = 4;
  public static final int This = 78;
  public static final int Suma = 16;
  public static final int Using = 35;
  public static final int ERROR = 92;
  public static final int Cadena = 8;
  public static final int Typedef = 82;
  public static final int T_dato = 6;
  public static final int Main = 31;
  public static final int Do = 11;
  public static final int Static = 73;
  public static final int Private = 64;
  public static final int Op_relacional = 21;
  public static final int P_coma = 33;
  public static final int Unsigned = 86;
  public static final int Signed = 71;
  public static final int Typeid = 83;
  public static final int Operator = 63;
  public static final int Short = 70;
  public static final int Template = 77;
  public static final int Case = 44;
  public static final int Volatile = 90;
  public static final int New = 62;
  public static final int Const = 52;
  public static final int Variables = 87;
  public static final int Continue = 53;
  public static final int Sizeof = 72;
  public static final int Dynamic_cast = 55;
  public static final int Auto = 46;
  public static final int If = 9;
  public static final int Dos_P = 12;
  public static final int EOF = 0;
  public static final int Virtual = 88;
  public static final int Catch = 48;
  public static final int Bool = 91;
  public static final int Throw = 79;
  public static final int Cout = 32;
  public static final int Typename = 84;
  public static final int Numero = 38;
  public static final int Struct = 75;
  public static final int Division = 19;
  public static final int Friend = 58;
  public static final int Doble_Menor = 40;
  public static final int Asm = 45;
  public static final int error = 1;
  public static final int Static_cast = 74;
  public static final int False = 57;
  public static final int Inline = 59;
  public static final int NameSpace = 36;
  public static final int Comillas = 3;
  public static final int Explicit = 56;
  public static final int Identificador = 34;
  public static final int Op_incremento = 23;
  public static final int Reinterpret_cast = 68;
  public static final int Include = 41;
  public static final int Class = 50;
  public static final int Cons_cast = 51;
  public static final int Register = 67;
  public static final int Palabra = 39;
  public static final int Delete = 54;
  public static final int Igual = 15;
  public static final int Union = 85;
  public static final int While = 13;
  public static final int Op_logico = 20;
  public static final int Switch = 76;
  public static final int Multiplicacion = 18;
  public static final int Protected = 65;
}

