
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 15 22:34:39 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Public = 67;
  public static final int Op_atribucion = 23;
  public static final int Parentesis_c = 27;
  public static final int Return = 70;
  public static final int Op_booleano = 25;
  public static final int Parentesis_a = 26;
  public static final int Llave_c = 29;
  public static final int Mutable = 62;
  public static final int Llave_a = 28;
  public static final int Libreria = 43;
  public static final int Linea = 2;
  public static final int Break = 48;
  public static final int Corchete_c = 31;
  public static final int True = 81;
  public static final int Corchete_a = 30;
  public static final int Long = 61;
  public static final int Default = 44;
  public static final int Char = 50;
  public static final int For = 15;
  public static final int Void = 90;
  public static final int Else = 11;
  public static final int Try = 82;
  public static final int Resta = 18;
  public static final int Int = 8;
  public static final int Doble_Mayor = 6;
  public static final int Espacio_de_Nombre = 38;
  public static final int Cin = 5;
  public static final int This = 79;
  public static final int Suma = 17;
  public static final int Using = 36;
  public static final int ERROR = 93;
  public static final int Cadena = 9;
  public static final int Typedef = 83;
  public static final int T_dato = 7;
  public static final int Main = 32;
  public static final int Do = 12;
  public static final int Static = 74;
  public static final int Do_cierre = 4;
  public static final int Private = 65;
  public static final int Op_relacional = 22;
  public static final int P_coma = 34;
  public static final int Unsigned = 87;
  public static final int Signed = 72;
  public static final int Typeid = 84;
  public static final int Operator = 64;
  public static final int Short = 71;
  public static final int Template = 78;
  public static final int Case = 45;
  public static final int Volatile = 91;
  public static final int New = 63;
  public static final int Const = 53;
  public static final int Variables = 88;
  public static final int Continue = 54;
  public static final int Sizeof = 73;
  public static final int Dynamic_cast = 56;
  public static final int Auto = 47;
  public static final int If = 10;
  public static final int Dos_P = 13;
  public static final int EOF = 0;
  public static final int Virtual = 89;
  public static final int Catch = 49;
  public static final int Bool = 92;
  public static final int Throw = 80;
  public static final int Cout = 33;
  public static final int Typename = 85;
  public static final int Numero = 39;
  public static final int Struct = 76;
  public static final int Division = 20;
  public static final int Friend = 59;
  public static final int Doble_Menor = 41;
  public static final int Asm = 46;
  public static final int error = 1;
  public static final int Static_cast = 75;
  public static final int False = 58;
  public static final int Inline = 60;
  public static final int NameSpace = 37;
  public static final int Comillas = 3;
  public static final int Explicit = 57;
  public static final int Identificador = 35;
  public static final int Op_incremento = 24;
  public static final int Reinterpret_cast = 69;
  public static final int Include = 42;
  public static final int Class = 51;
  public static final int Cons_cast = 52;
  public static final int Register = 68;
  public static final int Palabra = 40;
  public static final int Delete = 55;
  public static final int Igual = 16;
  public static final int Union = 86;
  public static final int While = 14;
  public static final int Op_logico = 21;
  public static final int Switch = 77;
  public static final int Multiplicacion = 19;
  public static final int Protected = 66;
}

